### ISSUE TITLE
Can't add feed route

### ISSUE THREAD

**Issue by JonathanReeve** [JonathanReeve/jonreeve.com-ema#3]
Adding `navItem SR_Feed "feed"` to the header doesn't work, since it complains that it "Couldn't match expected type 'R' with actual type 'SR'". This is because `navItem` takes `R` instead of `SR`. But it should take `SR`, since one of the possible nav items is a feed, and the SR_Feed isn't an `R`. This is tricky, it seems. @srid , any ideas?

**Comment by srid** [comment]
You can change `navItem` to take `SR` instead?
