### ISSUE TITLE
Fix permalinks

### ISSUE THREAD

**Issue by JonathanReeve** [JonathanReeve/jonreeve.com-ema#5]
For backwards compatibility with my current site, I need permalinks to look like `https://jonreeve.com/2022/03/best-practices-dissertation/`.

**Comment by JonathanReeve** [comment]
Oof, the problem I'm encountering here is that Ema needs to go both ways, i.e., encoding and decoding, and my filenames don't correspond to my URLs very precisely. So I can encode, but not decode: 

```haskell
-- | Convert "posts/2022-03-12-rethinking.org" to "2022/03/rethinking.html"
-- for backwards compatibility with my existing URLs.
permalink :: FilePath -> FilePath
permalink fp = year </> month </> rest -<.> ".html" where
  (year, month, _, rest) = case T.splitOn "-" (T.pack (takeFileName fp)) of
    y : m : d : title -> (T.unpack y, T.unpack m, T.unpack d, T.unpack $ T.intercalate "-" title)
    _                 -> error "Malformed filename"

-- | Convert "2022/03/rethinking.html" to "posts/2022-03-12-rethinking.org"
-- | XXX: wait, nevermind, this is impossible, since I'm not keeping track of the date. 
unPermalink :: FilePath -> FilePath
unPermaLink fp = error
```

@srid, what do you think? I guess one solution might be to move away from using this type of filename, and to just put dates in the document metadata. Then all the post files can be renamed using just their months. But this is less than ideal, since then the posts would get all out of order. 

Alternatively, I guess I could use something in the model which looks up the date, and uses that to reconstruct the filename?

**Comment by srid** [comment]
I'll take a look, and even update Ema itself.

**Comment by srid** [comment]
@JonathanReeve How are you going to decode that if you don't know the "day" part?

**Comment by srid** [comment]
You could just rename your source .org files to match that, TBH.

**Comment by srid** [comment]
> Alternatively, I guess I could use something in the model which looks up the date, and uses that to reconstruct the filename?

Yes, this is a good place where we need to "lookup" the model when decoding the routes. I've done this in 069f0ac - it is part of #6
